"""Create ``graphviz.js`` from the ``@hpcc-js/wasm-graphviz`` package.

Usage: ``python make_classic_script.py`` (see ``README.md`` in this directory).

The library is distributed as an ES module, but the DataOps report is opened
from the filesystem (``file://``), where browsers refuse to load local ES
modules. This script downloads the pinned version of the library and turns it
into a classic script that defines ``window.skrubGraphviz``: the final
``export`` statement is replaced by an assignment, and the whole code is wrapped
in a function so that it does not define global variables.

The script is meant to be written in a ``<script>`` element in the pages.
"""

import hashlib
import re
import urllib.request
from pathlib import Path

VERSION = "1.29.2"
URL = f"https://cdn.jsdelivr.net/npm/@hpcc-js/wasm-graphviz@{VERSION}/dist/index.js"
SHA256 = "550d9cd6ff429f5bd225316fe1faed4f852038c3e1ec609ce113af1f9379ce25"
OUTPUT_FILE = Path(__file__).resolve().parent / "graphviz.js"

HEADER = f"""\
/*
 * Generated by make_classic_script.py from @hpcc-js/wasm-graphviz {VERSION}
 * ({URL}), distributed under the Apache License 2.0 (see LICENSE).
 * The only changes are that the `export` statement was replaced by an
 * assignment to `window.skrubGraphviz` and the code is wrapped in a function.
 * Do not edit by hand.
 */
"""


def make_classic_script(source):
    """Turn the source of the ES module into a classic script.

    >>> script = make_classic_script("var a=1;export{a as Other,a as Graphviz};")
    >>> print(script[script.index("(function"):])
    (function () {
    var a=1;
    window.skrubGraphviz = {Graphviz: a};
    })();
    """
    export = re.search(r"export\s*\{([^}]*)\}\s*;?", source)
    graphviz_name = re.search(r"(\w+) as Graphviz\b", export.group(1)).group(1)
    source = source[: export.start()] + source[export.end() :]
    source = re.sub(r"//# sourceMappingURL=.*", "", source).strip()
    for forbidden in "</script", "<!--":
        if forbidden in source:
            raise ValueError(f"Cannot include the library in a <script>: {forbidden}")
    return (
        f"{HEADER}(function () {{\n"
        f"{source}\n"
        f"window.skrubGraphviz = {{Graphviz: {graphviz_name}}};\n"
        "})();\n"
    )


def main():
    with urllib.request.urlopen(URL) as response:
        content = response.read()
    if (digest := hashlib.sha256(content).hexdigest()) != SHA256:
        raise RuntimeError(f"Unexpected content for {URL}: sha256 is {digest}")
    OUTPUT_FILE.write_text(make_classic_script(content.decode("utf-8")), "utf-8")


if __name__ == "__main__":
    main()
